// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9_s7TVAHElvkjcne4ILE2OSYXONl4FTs',
    appId: '1:788717659527:web:b4bd725f4f5c538cc11f22',
    messagingSenderId: '788717659527',
    projectId: 'timetracker-2c608',
    authDomain: 'timetracker-2c608.firebaseapp.com',
    storageBucket: 'timetracker-2c608.appspot.com',
    measurementId: 'G-JW5G3331BB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqKvBeOoFYhPJFsv9TcBtqvLF0XX_r_Tk',
    appId: '1:788717659527:android:fc1e19bad7d8af56c11f22',
    messagingSenderId: '788717659527',
    projectId: 'timetracker-2c608',
    storageBucket: 'timetracker-2c608.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPAOaT8tg2UuzMMxML9kTsEMOPzXEoZmo',
    appId: '1:788717659527:ios:8f415479a3364a87c11f22',
    messagingSenderId: '788717659527',
    projectId: 'timetracker-2c608',
    storageBucket: 'timetracker-2c608.appspot.com',
    iosBundleId: 'com.example.tracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPAOaT8tg2UuzMMxML9kTsEMOPzXEoZmo',
    appId: '1:788717659527:ios:88a102dc89773720c11f22',
    messagingSenderId: '788717659527',
    projectId: 'timetracker-2c608',
    storageBucket: 'timetracker-2c608.appspot.com',
    iosBundleId: 'com.example.tracker.RunnerTests',
  );
}
